version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db

  web:
    build: ./flask
    image: dsairlines-app
    restart: always
    container_name: dsairlines-web
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/DSAirlines
      - SECRET_KEY=prod-secret-key-change-this
      - FLASK_APP=run.py
      - FLASK_ENV=production
